### ISSUE TITLE
The code at line 71  and 73 is a tad bit wrong 

### ISSUE THREAD

**Issue by ankitverma2211** [pjanaya/nodejs-express4-mysql#2]
User.update({ username: username,password: password},{where: {id: id} }).success(onSuccess).error(onError);

should be 

User.update({ username: username,password: password}, {id: user_id} ).success(onSuccess).error(onError);

same mistake at 73

**Comment by pjanaya** [comment]
Hi @ankitverma2211. At first, thanks for your comment. I saw your comment on my blog also, but I've been so busy all week. So sorry about that.

About this issue, you are totally right. The main problem is that Sequelize has been updated very quickly since I wrote this tutorial. When I wrote it the latest version was 1.7.x and now is 3.12.2.  A couple of months after I wrote the article Sequelize was updated to the major (and breaking) version 2.0. Around that time I updated the code to support the new version but I didn't change the package.json.

I've updated now the package.json, I've tried the code again and I confirm that everything is working now. So you have two options here: stick with the version 1.7.x and use the code you are proposing, or update to version 2.0 and use my code.

I hope this would be enough for you. Let me know if I can help with whatever.
